stages:
  - test
  - demos

default:
  tags:
    - csfw-minion

usage:
  stage: test
  script:
    - nix-shell --pure --run "git_recycle_bin.py --help"
    - nix-shell --pure --run "just --list"

unittest:
  stage: test
  script:
    - nix-shell --pure --run "just unittest"

demo0:
  stage: demos
  script:
    - nix-shell --pure --run "just demo0"

demo1:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1"

demo1_quiet:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_quiet"

demo1_verbose:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_verbose"

demo1_vverbose:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_vverbose"

demo2:
  stage: demos
  script:
    - nix-shell --pure --run "just demo2"

demo3:
  stage: demos
  script:
    - nix-shell --pure --run "just demo3"

demo4:
  stage: demos
  script:
    - nix-shell --pure --run "just demo4"

demo5:
  stage: demos
  script:
    - nix-shell --pure --run "just demo5"

demo6_note:
  stage: demos
  script:
    # Ensure we got origin remote via ssh -- avoid trouble/leaks with https tokens
    - git remote -vv
    - aux/git_add_ssh_remote.sh origin  # Create new 'origin_ssh'. 'origin' may be https
    - git remote remove origin
    - git remote rename origin_ssh origin
    - git remote -vv

    # This will actually push a note to src remote, so it is not local-only!
    # Not --pure so as to use host system's ssh client
    - nix-shell --run "just demo6_note"
