stages:
  - test
  - demos

default:
  tags:
    - csfw-minion

usage:
  stage: test
  script:
    - nix-shell --pure --run "git_recycle_bin.py --help"
    - nix-shell --pure --run "just --list"

unittest:
  stage: test
  script:
    - nix-shell --pure --run "just unittest"

demo0:
  stage: demos
  script:
    - nix-shell --pure --run "just demo0"

demo1:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1"

demo1_quiet:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_quiet"

demo1_verbose:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_verbose"

demo1_vverbose:
  stage: demos
  script:
    - nix-shell --pure --run "just demo1_vverbose"

demo2:
  stage: demos
  script:
    - nix-shell --pure --run "just demo2"

demo3:
  stage: demos
  script:
    - nix-shell --pure --run "just demo3"

demo4:
  stage: demos
  script:
    - nix-shell --pure --run "just demo4"

demo5:
  stage: demos
  script:
    - nix-shell --pure --run "just demo5"
