name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  NIX_PATH: "nixpkgs=channel:nixos-24.05"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Usage help
        run: nix-shell --pure --run "git_recycle_bin.py --help"
      - name: Just list
        run: nix-shell --pure --run "just --list"
      - name: Unit tests
        env:
          TZ: Europe/Copenhagen
        run: nix-shell --pure --run "just unittest"

  docs:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - name: Build documentation
        run: nix-shell --pure --run "just docs-html"
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html
      - uses: actions/deploy-pages@v2
